### ISSUE TITLE
install project, gulp watch go wrong...

### ISSUE THREAD

**Issue by javck2** [start-laravel/sb-admin-laravel-5#2]
When I try to use the install tutorial ,everything seems smooth.
But at the step of gulp watch , it shows an error and hangs out without finish..

Please help fix the error below , thanks~

![2015-04-29_19-02-52](https://cloud.githubusercontent.com/assets/12168926/7389670/c8504d4a-eea2-11e4-9784-642a72b9a389.png)

**Comment by sankhadeeproy007** [comment]
Hello, thanks for pointing it out. It was an issue with Font Awesome as the directory was renamed from font-awesome to fontawesome. I updated the gulpfile.js addressing the issue. Should work now. Keep me posted.

**Comment by javck2** [comment]
Hello, thanks for your kindly help.I try to modify gulpfile.js as you say and the problem was saved.
But the terminal is still hangout without backing to command accepting status when finished 'watch-assets'.
Is it normal?
At last ,I really appreciate for your support.
![2015-04-30_10-49-06](https://cloud.githubusercontent.com/assets/12168926/7405556/d1ea6cee-ef26-11e4-875e-c6e21b3bd58f.png)

**Comment by sankhadeeproy007** [comment]
What "gulp watch" does it that it checks the CSS and JS files for any changes and compiles them to your public folder. You can just use "gulp" instead if you want your terminal back. Or you can always open a new terminal.
